# automatically generated by the FlatBuffers compiler, do not modify
from .DynamicFloatTrack import DynamicFloatTrackT
from .FixedFloatTrack import FixedFloatTrackT
from .Framed16FloatTrack import Framed16FloatTrackT
from .Framed8FloatTrack import Framed8FloatTrackT


# namespace: Anim

class FloatTrack(object):
    NONE = 0
    FixedFloatTrack = 1
    DynamicFloatTrack = 2
    Framed16FloatTrack = 3
    Framed8FloatTrack = 4

def FloatTrackCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == FloatTrack().FixedFloatTrack:
        return FixedFloatTrackT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == FloatTrack().DynamicFloatTrack:
        return DynamicFloatTrackT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == FloatTrack().Framed16FloatTrack:
        return Framed16FloatTrackT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == FloatTrack().Framed8FloatTrack:
        return Framed8FloatTrackT.InitFromBuf(table.Bytes, table.Pos)
    return None
